[versions]
agp = "8.11.1"
ekaUiKit = "1.0.3"
#ekaUiKit = "0.0.1"
kotlin = "2.0.0"
coreKtx = "1.13.1"
appcompat = "1.7.1"
material = "1.6.0"
#records = "3.2.3"
records = "3.2.1"
composeShimmer = "1.3.3"
coil = "2.7.0"
gson = "2.10.1"
playServicesMlkitDocumentScanner = "16.0.0-beta1"
bouquet = "1.1.2"
accompanistPermissions = "0.25.1"
workRuntimeKtx = "2.8.1"
desugar_jdk_libs = "2.1.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
eka-ui-kit = { module = "com.github.eka-care:eka-ui-kit", version.ref = "ekaUiKit" }
#eka-ui-kit = { module = "com.eka.ui:ui", version.ref = "ekaUiKit" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "androidx.compose.material", name = "material", version.ref = "material" }
eka-health-records = { group = "com.github.eka-care", name = "eka-health-records-android", version.ref = "records" }
#eka-health-records = { group = "com.eka.records", name = "eka-records", version.ref = "records" }
compose-shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "composeShimmer" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
mlkit-scanner = { group = "com.google.android.gms", name = "play-services-mlkit-document-scanner", version.ref = "playServicesMlkitDocumentScanner" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
bouquet = { module = "io.github.grizzi91:bouquet", version.ref = "bouquet" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }